# Generated by Django 3.1.1 on 2020-11-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='source',
            field=models.IntegerField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='target',
            field=models.IntegerField(max_length=16),
        ),
    ]
